import { Injectable, Logger } from '@nestjs/common';
import type { SourceString, GeneratedFile } from '../adapters/adapter.types';

/**
 * RuntimeGeneratorService — Pass 2 of the two-pass i18n transformation.
 *
 * Generates three kinds of in-memory files:
 *   1. `lib/i18n.ts`                   — the zero-dep t() helper
 *   2. `public/locales/{locale}.json`  — flat { hash: translatedText } dictionaries
 *   3. Root layout patch               — framework-specific locale loader injection
 *
 * All output is returned as GeneratedFile[] — never written to workspace.
 * The pipeline (Chunk 12) passes these to Git delivery (Chunk 11).
 */
@Injectable()
export class RuntimeGeneratorService {
    private readonly logger = new Logger(RuntimeGeneratorService.name);

    /**
     * Generates the `lib/i18n.ts` helper — a zero-dependency t() function.
     * `t("unknown_hash")` returns the hash itself as fallback; never crashes.
     */
    generateI18nHelper(): GeneratedFile {
        const content = `// Auto-generated by locales — do not edit manually
let _translations: Record<string, string> = {};

/**
 * Load a locale dictionary into the translation runtime.
 * Call this once in your root layout/entry with the imported locale JSON.
 */
export function loadTranslations(map: Record<string, string>): void {
  _translations = map;
}

/**
 * Returns the translated string for the given hash.
 * Falls back to the hash itself if no translation is found — never crashes.
 */
export function t(hash: string): string {
  return _translations[hash] ?? hash;
}
`;
        return { filePath: 'lib/i18n.ts', content };
    }

    /**
     * Generates `public/locales/{locale}.json` — flat hash→translation dictionary.
     * Only includes strings that have a non-empty translation.
     */
    generateLocaleJson(
        strings: SourceString[],
        translations: Map<string, string>, // hash → translatedText
        targetLocale: string,
    ): GeneratedFile {
        const dict: Record<string, string> = {};
        for (const s of strings) {
            const translated = translations.get(s.hash);
            if (translated) dict[s.hash] = translated;
        }

        const content = JSON.stringify(dict, null, 2);
        this.logger.debug(`Generated locale JSON for ${targetLocale}: ${Object.keys(dict).length} keys`);

        return {
            filePath: `public/locales/${targetLocale}.json`,
            content,
        };
    }

    /**
     * Generates a patched root layout that loads translations on startup.
     * The patch is framework-specific — each adapter passes its name.
     *
     * Supported: nextjs-app-router, nextjs-pages-router, vite-react, remix.
     */
    generateLayoutPatch(
        adapterName: string,
        entryPoint: string,
        locales: string[],
    ): GeneratedFile {
        const localeList = locales.map((l) => `'${l}'`).join(', ');

        switch (adapterName) {
            case 'nextjs-app-router':
                return this.appRouterPatch(entryPoint, localeList);
            case 'nextjs-pages-router':
                return this.pagesRouterPatch(entryPoint, localeList);
            case 'vite-react':
                return this.viteReactPatch(entryPoint, localeList);
            case 'remix':
                return this.remixPatch(entryPoint, localeList);
            default:
                this.logger.warn(`Unknown adapter "${adapterName}" — generating generic patch`);
                return this.genericPatch(entryPoint, localeList);
        }
    }

    // ── Framework-specific layout patchers ──────────────────────────────────

    private appRouterPatch(entryPoint: string, localeList: string): GeneratedFile {
        const content = `// Auto-generated by locales — i18n locale loader for Next.js App Router
import { loadTranslations } from '../lib/i18n';

const SUPPORTED_LOCALES = [${localeList}] as const;
type SupportedLocale = typeof SUPPORTED_LOCALES[number];

async function getTranslations(locale: string): Promise<Record<string, string>> {
  const supported = SUPPORTED_LOCALES.includes(locale as SupportedLocale)
    ? (locale as SupportedLocale)
    : SUPPORTED_LOCALES[0];
  try {
    const dict = await import(\`../../public/locales/\${supported}.json\`);
    return dict.default ?? dict;
  } catch {
    return {};
  }
}

// Wrap this around your RootLayout component to activate i18n:
//
// export default async function RootLayout({ children, params }: {...}) {
//   const locale = params.locale ?? 'en';
//   loadTranslations(await getTranslations(locale));
//   return (...existing layout jsx...);
// }
//
// See: https://nextjs.org/docs/app/building-your-application/routing/internationalization

export { getTranslations };
`;
        return { filePath: entryPoint.replace('layout.tsx', 'i18n-loader.ts'), content };
    }

    private pagesRouterPatch(entryPoint: string, localeList: string): GeneratedFile {
        const content = `// Auto-generated by locales — i18n locale loader for Next.js Pages Router
import { loadTranslations } from '../lib/i18n';

const SUPPORTED_LOCALES = [${localeList}] as const;

export async function loadLocale(locale: string): Promise<void> {
  const supported = (SUPPORTED_LOCALES as readonly string[]).includes(locale)
    ? locale
    : SUPPORTED_LOCALES[0];
  try {
    const dict = await import(\`../../public/locales/\${supported}.json\`);
    loadTranslations(dict.default ?? dict);
  } catch {
    loadTranslations({});
  }
}

// Usage in _app.tsx:
// import { loadLocale } from './i18n-loader';
// App.getInitialProps = async ({ ctx }) => {
//   await loadLocale(ctx.locale ?? 'en');
//   return {};
// };
`;
        return { filePath: entryPoint.replace('_app.tsx', 'i18n-loader.ts'), content };
    }

    private viteReactPatch(entryPoint: string, localeList: string): GeneratedFile {
        const content = `// Auto-generated by locales — i18n locale loader for Vite + React
import { loadTranslations } from '../lib/i18n';

const SUPPORTED_LOCALES = [${localeList}] as const;

export async function initI18n(locale = navigator.language.split('-')[0]): Promise<void> {
  const supported = (SUPPORTED_LOCALES as readonly string[]).includes(locale)
    ? locale
    : SUPPORTED_LOCALES[0];
  try {
    const dict = await import(\`../public/locales/\${supported}.json\`);
    loadTranslations(dict.default ?? dict);
  } catch {
    loadTranslations({});
  }
}

// Usage in main.tsx:
// import { initI18n } from './i18n-loader';
// initI18n().then(() => {
//   ReactDOM.createRoot(document.getElementById('root')!).render(<App />);
// });
`;
        return { filePath: entryPoint.replace('main.tsx', 'i18n-loader.ts').replace('index.tsx', 'i18n-loader.ts'), content };
    }

    private remixPatch(entryPoint: string, localeList: string): GeneratedFile {
        const content = `// Auto-generated by locales — i18n locale loader for Remix
import { loadTranslations } from '../lib/i18n';

const SUPPORTED_LOCALES = [${localeList}] as const;

export async function loadLocale(locale: string): Promise<void> {
  const supported = (SUPPORTED_LOCALES as readonly string[]).includes(locale)
    ? locale
    : SUPPORTED_LOCALES[0];
  try {
    const dict = await import(\`../../public/locales/\${supported}.json\`);
    loadTranslations(dict.default ?? dict);
  } catch {
    loadTranslations({});
  }
}

// Usage in root.tsx loader:
// export const loader = async ({ request }: LoaderFunctionArgs) => {
//   const locale = new URL(request.url).searchParams.get('lang') ?? 'en';
//   await loadLocale(locale);
//   return null;
// };
`;
        return { filePath: entryPoint.replace('root.tsx', 'i18n-loader.ts'), content };
    }

    private genericPatch(entryPoint: string, localeList: string): GeneratedFile {
        const content = `// Auto-generated by locales — generic i18n locale loader
import { loadTranslations } from '../lib/i18n';

const SUPPORTED_LOCALES = [${localeList}] as const;

export async function loadLocale(locale: string): Promise<void> {
  const supported = (SUPPORTED_LOCALES as readonly string[]).includes(locale)
    ? locale
    : SUPPORTED_LOCALES[0];
  try {
    const dict = await import(\`../public/locales/\${supported}.json\`);
    loadTranslations(dict.default ?? dict);
  } catch {
    loadTranslations({});
  }
}
`;
        return { filePath: 'src/i18n-loader.ts', content };
    }
}
