/**
 * Core types for the Framework Adapter Registry system.
 * All adapters and the registry operate on these shared contracts.
 */

/** Package.json dependencies / devDependencies map keyed by package name. */
export type DepsMap = Record<string, string>;

/** Result of an adapter's detection attempt for a given repository. */
export interface DetectionResult {
  /** Adapter name (matches FrameworkAdapter.name). */
  name: string;
  /** Confidence score 0.0–1.0. Adapters must reach >= 0.7 to qualify. */
  confidence: number;
}

/** A user-facing string extracted from a source file via Babel AST. */
export interface SourceString {
  /** SHA-256 hex of trimmed, NFC-normalised sourceText. */
  hash: string;
  sourceText: string;
  filePath: string;
  /** Babel node type: JSXText | JSXAttribute | StringLiteral | TemplateLiteral */
  nodeType: string;
  /** Parent component name or attribute name for context. */
  context: string;
}

/** A source file with content that has been modified by a code mod. */
export interface ModifiedFile {
  filePath: string;
  content: string;
}

/** A file generated by the adapter (runtime helper, routing middleware, etc.). */
export interface GeneratedFile {
  filePath: string;
  content: string;
}

/** A file ready for a Git commit (Git blob mode 100644 = regular file). */
export interface FileChange {
  path: string;
  content: string;
  mode: '100644';
}

/** Configuration passed to generateRuntime(). */
export interface RuntimeConfig {
  defaultLocale: string;
  entryPoint: string;
}

/**
 * FrameworkAdapter — the contract every adapter must satisfy.
 *
 * Chunk 4 implements: detect() and getEntryPoint().
 * The remaining methods throw NotImplementedException until their respective
 * implementation chunks (5, 9, 10) fill them in.
 */
export interface FrameworkAdapter {
  /** Unique adapter identifier, e.g. "nextjs-app-router". */
  readonly name: string;

  /**
   * Statically detects whether this adapter matches the repository.
   * Synchronous — receives pre-parsed deps and file path list, no I/O.
   */
  detect(deps: DepsMap, filePaths: string[]): DetectionResult;

  /**
   * Returns the path of the app entry point within the repo,
   * or null if none can be determined from the file list.
   */
  getEntryPoint(filePaths: string[]): string | null;

  /** Scans all relevant files and returns extracted user-facing strings. */
  extractStrings(
    filePaths: string[],
    readFile: (path: string) => Promise<string>,
  ): Promise<SourceString[]>;

  /** Applies t("hash") code mods to the modified file set. */
  applyCodeMod(
    files: ModifiedFile[],
    strings: SourceString[],
  ): Promise<ModifiedFile[]>;

  /** Generates the t() helper and locale loader files. */
  generateRuntime(config: RuntimeConfig, locales: string[]): GeneratedFile[];

  /** Generates middleware, hreflang tags, and html lang attribute helpers. */
  generateRouting(locales: string[]): GeneratedFile[];
}
