import { Injectable } from '@nestjs/common';
import type { DepsMap, DetectionResult, GeneratedFile } from './adapter.types';
import { BaseAdapter } from './base.adapter';
import { ExtractionService } from '../extraction/extraction.service';
import { CodeModService } from '../code-mod/code-mod.service';
import { RuntimeGeneratorService } from '../code-mod/runtime-generator.service';

/**
 * Next.js App Router adapter.
 * Detection: `next` dep + `app/layout.tsx` in file tree. Confidence 0.95.
 * Beats Pages Router (0.90) in hybrid repos.
 */
@Injectable()
export class NextjsAppRouterAdapter extends BaseAdapter {
  readonly name = 'nextjs-app-router';

  constructor(
    extractionService: ExtractionService,
    codeModService: CodeModService,
    runtimeGenerator: RuntimeGeneratorService,
  ) {
    super(extractionService, codeModService, runtimeGenerator);
  }

  detect(deps: DepsMap, filePaths: string[]): DetectionResult {
    if (!('next' in deps)) return { name: this.name, confidence: 0 };
    const hasAppLayout = filePaths.some(
      (p) =>
        p === 'app/layout.tsx' ||
        p === 'app/layout.jsx' ||
        p === 'src/app/layout.tsx' ||
        p === 'src/app/layout.jsx',
    );
    return { name: this.name, confidence: hasAppLayout ? 0.95 : 0.75 };
  }

  getEntryPoint(filePaths: string[]): string | null {
    return (
      filePaths.find(
        (p) =>
          p === 'app/layout.tsx' ||
          p === 'app/layout.jsx' ||
          p === 'src/app/layout.tsx' ||
          p === 'src/app/layout.jsx',
      ) ?? null
    );
  }

  protected getDefaultEntryPoint(): string {
    return 'app/layout.tsx';
  }

  generateRouting(locales: string[]): GeneratedFile[] {
    const localeList = locales.map((l) => `'${l}'`).join(', ');
    const defaultLocale = locales[0] ?? 'en';

    const middlewareContent = `// Auto-generated by locales — i18n routing middleware
import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';

const locales = [${localeList}];
const defaultLocale = '${defaultLocale}';

export function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl;

  const pathnameHasLocale = locales.some(
    (locale) => pathname.startsWith(\`/\${locale}/\`) || pathname === \`/\${locale}\`
  );

  if (pathnameHasLocale) return;

  const locale = defaultLocale;
  request.nextUrl.pathname = \`/\${locale}\${pathname}\`;
  return NextResponse.redirect(request.nextUrl, 301);
}

export const config = {
  matcher: ['/((?!_next|api|favicon.ico).*)'],
};
`;

    const seoContent = `// Auto-generated by locales — SEO Head tags
import * as React from 'react';

export function I18nSeo({ currentPath, domain }: { currentPath: string, domain: string }) {
  const locales = [${localeList}];
  const cleanPath = currentPath.replace(/^\\/[a-z]{2}\\//, '/');

  return (
    <React.Fragment>
      {locales.map(loc => (
        <link key={loc} rel="alternate" hrefLang={loc} href={\`\${domain}/\${loc}\${cleanPath}\`} />
      ))}
      <link rel="alternate" hrefLang="x-default" href={\`\${domain}/en\${cleanPath}\`} />
    </React.Fragment>
  );
}
`;

    return [
      { filePath: 'middleware.ts', content: middlewareContent },
      { filePath: 'components/I18nSeo.tsx', content: seoContent },
    ];
  }
}
