import { Injectable } from '@nestjs/common';
import type { DepsMap, DetectionResult, GeneratedFile } from './adapter.types';
import { BaseAdapter } from './base.adapter';
import { ExtractionService } from '../extraction/extraction.service';
import { CodeModService } from '../code-mod/code-mod.service';
import { RuntimeGeneratorService } from '../code-mod/runtime-generator.service';

/**
 * Remix adapter.
 * Detection: `@remix-run/react` dep + `app/root.tsx`. Confidence 0.95.
 */
@Injectable()
export class RemixAdapter extends BaseAdapter {
  readonly name = 'remix';

  constructor(
    extractionService: ExtractionService,
    codeModService: CodeModService,
    runtimeGenerator: RuntimeGeneratorService,
  ) {
    super(extractionService, codeModService, runtimeGenerator);
  }

  detect(deps: DepsMap, filePaths: string[]): DetectionResult {
    if (!('@remix-run/react' in deps))
      return { name: this.name, confidence: 0 };
    const hasRoot = filePaths.some(
      (p) =>
        p === 'app/root.tsx' ||
        p === 'app/root.jsx' ||
        p === 'app/root.ts' ||
        p === 'app/root.js',
    );
    return { name: this.name, confidence: hasRoot ? 0.95 : 0.8 };
  }

  getEntryPoint(filePaths: string[]): string | null {
    return (
      filePaths.find(
        (p) =>
          p === 'app/root.tsx' ||
          p === 'app/root.jsx' ||
          p === 'app/root.ts' ||
          p === 'app/root.js',
      ) ?? null
    );
  }

  protected getDefaultEntryPoint(): string {
    return 'app/root.tsx';
  }

  generateRouting(locales: string[]): GeneratedFile[] {
    const localeList = locales.map((l) => `'${l}'`).join(', ');

    const seoContent = `// Auto-generated by locales — SEO Head tags
import * as React from 'react';

export function I18nSeo({ currentPath, domain }: { currentPath: string, domain: string }) {
  const locales = [${localeList}];
  const cleanPath = currentPath.replace(/^\\/[a-z]{2}\\//, '/');

  return (
    <React.Fragment>
      {locales.map(loc => (
        <link key={loc} rel="alternate" hrefLang={loc} href={\`\${domain}/\${loc}\${cleanPath}\`} />
      ))}
      <link rel="alternate" hrefLang="x-default" href={\`\${domain}/en\${cleanPath}\`} />
    </React.Fragment>
  );
}
`;

    return [{ filePath: 'app/components/I18nSeo.tsx', content: seoContent }];
  }
}
