import { Injectable } from '@nestjs/common';
import type { DepsMap, DetectionResult, GeneratedFile } from './adapter.types';
import { BaseAdapter } from './base.adapter';
import { ExtractionService } from '../extraction/extraction.service';
import { CodeModService } from '../code-mod/code-mod.service';
import { RuntimeGeneratorService } from '../code-mod/runtime-generator.service';

/**
 * Vite + React adapter.
 * Detection: `vite` dep + `react` dep + vite.config.* + NOT `next`. Confidence 0.95.
 */
@Injectable()
export class ViteReactAdapter extends BaseAdapter {
  readonly name = 'vite-react';

  constructor(
    extractionService: ExtractionService,
    codeModService: CodeModService,
    runtimeGenerator: RuntimeGeneratorService,
  ) {
    super(extractionService, codeModService, runtimeGenerator);
  }

  detect(deps: DepsMap, filePaths: string[]): DetectionResult {
    if (!('vite' in deps) || !('react' in deps) || 'next' in deps) {
      return { name: this.name, confidence: 0 };
    }
    const hasViteConfig = filePaths.some(
      (p) =>
        p === 'vite.config.ts' ||
        p === 'vite.config.js' ||
        p === 'vite.config.mts' ||
        p === 'vite.config.mjs',
    );
    return { name: this.name, confidence: hasViteConfig ? 0.95 : 0.75 };
  }

  getEntryPoint(filePaths: string[]): string | null {
    return (
      filePaths.find(
        (p) =>
          p === 'src/main.tsx' ||
          p === 'src/main.jsx' ||
          p === 'src/index.tsx' ||
          p === 'src/index.jsx',
      ) ?? null
    );
  }

  protected getDefaultEntryPoint(): string {
    return 'src/main.tsx';
  }

  generateRouting(locales: string[]): GeneratedFile[] {
    const localeList = locales.map((l) => `'${l}'`).join(', ');

    const seoContent = `// Auto-generated by locales — SEO Head tags
import * as React from 'react';

export function I18nSeo({ currentPath, domain }: { currentPath: string, domain: string }) {
  const locales = [${localeList}];
  const cleanPath = currentPath.replace(/^\\/[a-z]{2}\\//, '/');

  return (
    <React.Fragment>
      {locales.map(loc => (
        <link key={loc} rel="alternate" hrefLang={loc} href={\`\${domain}/\${loc}\${cleanPath}\`} />
      ))}
      <link rel="alternate" hrefLang="x-default" href={\`\${domain}/en\${cleanPath}\`} />
    </React.Fragment>
  );
}
`;

    return [{ filePath: 'src/I18nSeo.tsx', content: seoContent }];
  }
}
